#!/usr/bin/env ansible-playbook

##############################################################
# Author: Gholamreza Sabery Tabrizy
# Email: reza_sabery_89@yahoo.com
# Project Repository: https://github.com/ghrst/Kamailio-HA
##############################################################

- name: This play installs and configures MySQL Server for Kamailio. 
  hosts: mysql
  vars_files:
    - settings.yml
  tasks:
    - name: Installing mysql-server
      apt: pkg=mysql-server update_cache=yes
    
    - name: Update mysql root password
      mysql_user: 
        name: root
        host: "{{ item }}"
        password: "{{mySqlRootPass}}"
        login_user: root
        login_password: "{{mySqlRootPass}}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
        
    - name: Adding Kamailio's database user
      mysql_user:
        name: "{{mySqlKamailioUser}}"
        host: "{{item}}"
        password: "{{mySqlKamailioPass}}"
        login_user: root
        login_password: "{{mySqlRootPass}}"
      with_items: 
        - 127.0.0.1
        - "{{kamailioPublicIP}}"
        - localhost
         
        
