#!/usr/bin/env ansible-playbook

##############################################################
# Author: Gholamreza Sabery Tabrizy
# Email: reza_sabery_89@yahoo.com
# Project Repository: https://github.com/ghrst/Kamailio-HA
##############################################################

- name: Using this play you can deploy a cluster of RTPProxy servers to be usd with your Kamailio servers
  hosts: rtpproxy
  vars_files:
    - settings.yml
  tasks:
    
