#Mysql Settings
mySqlRootPass: password
mySqlKamailioUser: kamailiouser
mySqlKamailioPass: password
mySqlHost: "192.168.120.79"
mySqlBindIP: "{{mySqlHost}}"

#Allowed IP addresses to be connected to remote MySQL server
#FIXME:: These IP addresses should be inferred automatically. Anyway creating Kamailio's DB using two hosts will cause problems.
kam1IP: "192.168.120.66"
kam2IP: "192.168.120.76"


#Kamailio-related settings
kamailioSrcPath: /usr/local/src/kamailio
kamailioHomeDir: /var/run/kamailio
kamailioDbURL: mysql://{{mySqlKamailioUser}}:{{mySqlKamailioPass}}@{{mySqlHost}}/kamailio
kamailioSourceUrl: http://www.kamailio.org/pub/kamailio/4.1.1/src/kamailio-4.1.1_src.tar.gz
kamailioVirtualIP: "192.168.120.90"
kamailioVirtualIPNetMask: "255.255.255.0"
kamailioVirtualIPBroadCast: "192.168.120.255"
kamailioPublicIP: "192.168.120.90"
kamailioSIPDomain: "{{kamailioPublicIP}}"


#Other
preferencesPath: /etc/apt/preferences.d/
mtCastAddr: "239.0.0.95"


#CIB
cibPath: "/usr/local/src/"